/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as SettingsAccountRouteImport } from './routes/settings/account'
import { Route as ProjectsNewRouteImport } from './routes/projects/new'
import { Route as ProjectsIdRouteImport } from './routes/projects/$id'
import { Route as ProjectsIdVideosRouteImport } from './routes/projects/$id.videos'
import { Route as ProjectsIdEditRouteImport } from './routes/projects/$id.edit'
import { Route as ProjectsIdVideosVideoIdRouteImport } from './routes/projects/$id.videos.$videoId'

const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdVideosRoute = ProjectsIdVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdEditRoute = ProjectsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdVideosVideoIdRoute = ProjectsIdVideosVideoIdRouteImport.update({
  id: '/$videoId',
  path: '/$videoId',
  getParentRoute: () => ProjectsIdVideosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/success': typeof SuccessRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/settings/account': typeof SettingsAccountRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$id/edit': typeof ProjectsIdEditRoute
  '/projects/$id/videos': typeof ProjectsIdVideosRouteWithChildren
  '/projects/$id/videos/$videoId': typeof ProjectsIdVideosVideoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/success': typeof SuccessRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/settings/account': typeof SettingsAccountRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$id/edit': typeof ProjectsIdEditRoute
  '/projects/$id/videos': typeof ProjectsIdVideosRouteWithChildren
  '/projects/$id/videos/$videoId': typeof ProjectsIdVideosVideoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/success': typeof SuccessRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/settings/account': typeof SettingsAccountRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$id/edit': typeof ProjectsIdEditRoute
  '/projects/$id/videos': typeof ProjectsIdVideosRouteWithChildren
  '/projects/$id/videos/$videoId': typeof ProjectsIdVideosVideoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/success'
    | '/projects/$id'
    | '/projects/new'
    | '/settings/account'
    | '/projects'
    | '/projects/$id/edit'
    | '/projects/$id/videos'
    | '/projects/$id/videos/$videoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/success'
    | '/projects/$id'
    | '/projects/new'
    | '/settings/account'
    | '/projects'
    | '/projects/$id/edit'
    | '/projects/$id/videos'
    | '/projects/$id/videos/$videoId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/success'
    | '/projects/$id'
    | '/projects/new'
    | '/settings/account'
    | '/projects/'
    | '/projects/$id/edit'
    | '/projects/$id/videos'
    | '/projects/$id/videos/$videoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SuccessRoute: typeof SuccessRoute
  ProjectsIdRoute: typeof ProjectsIdRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
  SettingsAccountRoute: typeof SettingsAccountRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/videos': {
      id: '/projects/$id/videos'
      path: '/videos'
      fullPath: '/projects/$id/videos'
      preLoaderRoute: typeof ProjectsIdVideosRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/edit': {
      id: '/projects/$id/edit'
      path: '/edit'
      fullPath: '/projects/$id/edit'
      preLoaderRoute: typeof ProjectsIdEditRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/videos/$videoId': {
      id: '/projects/$id/videos/$videoId'
      path: '/$videoId'
      fullPath: '/projects/$id/videos/$videoId'
      preLoaderRoute: typeof ProjectsIdVideosVideoIdRouteImport
      parentRoute: typeof ProjectsIdVideosRoute
    }
  }
}

interface ProjectsIdVideosRouteChildren {
  ProjectsIdVideosVideoIdRoute: typeof ProjectsIdVideosVideoIdRoute
}

const ProjectsIdVideosRouteChildren: ProjectsIdVideosRouteChildren = {
  ProjectsIdVideosVideoIdRoute: ProjectsIdVideosVideoIdRoute,
}

const ProjectsIdVideosRouteWithChildren =
  ProjectsIdVideosRoute._addFileChildren(ProjectsIdVideosRouteChildren)

interface ProjectsIdRouteChildren {
  ProjectsIdEditRoute: typeof ProjectsIdEditRoute
  ProjectsIdVideosRoute: typeof ProjectsIdVideosRouteWithChildren
}

const ProjectsIdRouteChildren: ProjectsIdRouteChildren = {
  ProjectsIdEditRoute: ProjectsIdEditRoute,
  ProjectsIdVideosRoute: ProjectsIdVideosRouteWithChildren,
}

const ProjectsIdRouteWithChildren = ProjectsIdRoute._addFileChildren(
  ProjectsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SuccessRoute: SuccessRoute,
  ProjectsIdRoute: ProjectsIdRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
  SettingsAccountRoute: SettingsAccountRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
